apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-commerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: niccco/order-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: MONGODB_URI
            - name: PRODUCT_SERVICE_HOST
              value: "product-service"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cloud-commerce
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: cloud-commerce
data:
  MONGODB_URI: "mongodb://rootuser:rootpass@mongodb:27017/order-db?authSource=admin"