services:
  mongo-db:
    container_name: mongo-db
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - '27017:27017'
    volumes:
      - mongo-db-data:/data/db
volumes:
  mongo-db-data: