spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

server:
  port:
    8081

openapi:
  service:
    title: product-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
